### ISSUE TITLE
error in Pong.java computePosition method

### ISSUE THREAD

**Issue by DomenickD3** [lerks/Pong#2]
In Pong.java on line you accidentally have two checks for player.getType() == Player.MOUSE

`// KEYBOARD
		else if (player.getType() == Player.MOUSE) {`

change to -->

`// KEYBOARD
		else if (player.getType() == Player.KEYBOARD) {`

and everything works as expected.

P.S. on line 63 you declare a variable `int base` which is never used.  On line 9 you have an import `import javax.swing.JOptionPane;` which is never used.

**Comment by lw** [comment]
Fixed in 42bfa437e5022af59cfb9187715a80b5998092d1.
